### ISSUE TITLE
Can't Find g502 Hero

### ISSUE THREAD

**Issue by ekomlenovic** [ysph/gHub-GUI#12]
Hi everyone, 

i can't find G502 hero.
(master)$ sudo ./ghub-gui
Error: Cannot find any logitech mouse. LIBUSB_SUCCESS / LIBUSB_TRANSFER_COMPLETED

I saw it was not implemented yet.
![image](https://github.com/ysph/gHub-GUI/assets/14351506/c67470cb-fd2b-45c7-92f0-4bd112ee7fe8)

Do you plan to add it soon ?

**Comment by ekomlenovic** [comment]
Maybe you should add a not implemented error, i thinks it's more userfriendly.

I can make a pull request later if you want

**Comment by ekomlenovic** [comment]
https://github.com/ysph/gHub-GUI/pull/13

**Comment by ysph** [comment]
> #13

Merged!
