### ISSUE TITLE
G203 Device is not found. "Same issue"

### ISSUE THREAD

**Issue by AndyStreams** [ysph/gHub-GUI#4]
![Screenshot from 2021-11-01 17-54-44](https://user-images.githubusercontent.com/93365364/139753462-1c226770-e464-4a40-8825-72e86d8da554.png)
"Can't find a Logitech Device"
This software is missing the Logitech G-203 "Part Number 910-004842" Ive tried unplugging the mouse, Ive tried Uninstalling & Reinstalling the mouse drivers and that didn't seem to work does this software only work with a certain type of mouse or most or what?? could you maybe fix this problem?

**Comment by ysph** [comment]
The commit [9fabe8e](https://github.com/ysph/gHub-GUI/commit/9fabe8e33130e73d8647c8309687a5a162c4b452) solved the issue.
